### ISSUE TITLE
How to edit conditions?

### ISSUE THREAD

**Issue by ntodorov** [vinzdeveloper/json-rule-editor#14]
Hi,

First a cool project you have here!

I was trying your Rent-Rules.json with the UI https://www.json-rule-editor.com/ and I cannot find a way to edit the conditions. Those are my steps:

1. I click View Conditions in the first row of Decisions.
That shows the graph.
2. I click the edit icon in the right top of the graph.
3. It displays the same graph with buttons on top for operators facts and outcome, and displays the original graph bellow, but how do you edit the condition itself? For example to make the rooms to equal 2? Clicking the "Edit Conditions" does not do anything.

What I'm missing?

Thanks,
Nik

**Comment by vinzdeveloper** [comment]
Thanks @ntodorov ,

If you want to change the existing fact conditions, you have to remove the particular node as below

1) Select the fact node where you need amendments
2) Click Remove tab in "Step2: "Add / Remove Facts.
3) You have to add new fact under relevant parent fact node.

Having edit button to change fact actually next to each node creates confusion and become messy. so we have to follow above process in order to change the existing fact value / conditions.

Hope it makes sense!

**Comment by vinzdeveloper** [comment]
No fix required!!
